version: '3.4'

services:
  microrabbit.mvc:
    image: ${DOCKER_REGISTRY-}microrabbitmvc
    build:
      context: .
      dockerfile: MicroRabbit.MVC/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/MicroRabbit.MVC.pfx
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro

  microrabbit.banking.api:
    image: ${DOCKER_REGISTRY-}microrabbitbankingapi
    build:
      context: .
      dockerfile: MicroRabbit.Banking.Api/Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/MicroRabbit.Banking.Api.pfx
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro

  microrabbit.transfer.api:
    image: ${DOCKER_REGISTRY-}microrabbittransferapi
    build:
      context: .
      dockerfile: MicroRabbit.Transfer.Api/Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/MicroRabbit.Transfer.Api.pfx
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro
  
  nginxproxy:
    image: ${DOCKER_REGISTRY-}nginxproxy
    build:
      context: .
      dockerfile: Nginx/Dockerfile
    ports:
        - "80:80"
    depends_on:
      - microrabbit.mvc
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 30s
        timeout: 10s
        retries: 5

  rabbitmq: # login guest:guest
    image: rabbitmq:management
    ports:
    - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5